# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bors"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Richardson"]
  s.date = "2013-01-25"
  s.description = "Wrapper for the Vowpal Wabbit library"
  s.email = "sam@richardson.co.nz"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bors.gemspec",
    "lib/bors.rb",
    "lib/bors/command_line.rb",
    "lib/bors/example.rb",
    "lib/bors/example/feature.rb",
    "lib/bors/exceptions.rb",
    "lib/bors/math.rb",
    "lib/bors/result.rb",
    "lib/bors/result/samples.rb",
    "lib/bors/result/settings.rb",
    "lib/bors/result/statistics.rb",
    "spec/bors.rb",
    "spec/bors/example.rb",
    "spec/bors/example/feature.rb",
    "spec/bors/result.rb",
    "spec/bors/result/samples.rb",
    "spec/bors/result/settings.rb",
    "spec/bors/result/statistics.rb",
    "spec/fixtures/examples.txt",
    "spec/fixtures/result.txt",
    "spec/runner.rb",
    "spec/spec_helper.rb",
    "spec/tutorial.rb"
  ]
  s.homepage = "http://github.com/rodeoclash/bors"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Wrapper for the Vowpal Wabbit library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oj>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
    else
      s.add_dependency(%q<oj>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<oj>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<bundler>, [">= 0"])
  end
end

